# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /eboot
  # 优雅停机，默认是IMMEDIATE立即停机
  shutdown: graceful
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    connection-timeout: 60000
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 800
      min-spare: 30
#  文件上传路径
  file-path-avatar: /opt/eboot/avatar/
  file-path-upload: /opt/eboot/uploadPath/
  file-path-download: /opt/eboot/downloadPath/
  file-path-temp: ${server.file-path-download}temp/
  # swagger开关
  swagger:
    enabled: true
  # 操作日志记录开关
  operate-log:
    enabled: true
# Spring配置
spring:
  application:
    name: @project.name@
  profiles:
    active: dev
  # 文件上传
  servlet:
     multipart:
# springboot MultipartFile和fastjson冲突，解析不出上传的文件，所以选择关闭spring文件上传，选用commons-fileupload
       enabled: false
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  100MB
       location: ${server.file-path-upload}
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    static-path-pattern: /static/**
    view:
      # 给返回的页面添加后缀名
      suffix: .html
      # 定位模板的目录
      prefix: classpath:/templates/
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #服务注册到nacos
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  boot:
#    admin:
#      client:
#        url: http://192.168.137.67:8769/
#        username: admin
#        password: admin#8769
  jmx:
    enabled: true
  cache:
    redis:
      cache-null-values: off
      use-key-prefix: true
      key-prefix: ${spring.application.name}
      time-to-live: 1H
  session:
    store-type: redis
    timeout: 30M
  mail:
    host: smtp.qq.com #SMTP服务器地址
    username: zmzhou8 #登陆账号
    password: 123456 #登陆密码（或授权码）
    properties:
      from: zmzhou8@qq.com #邮件发信人（即真实邮箱）
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: WAvvQhWyDqWah-nxtNgPAA
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # Token前缀字符
  prefix: easybooy-
  # 配置不需要认证的接口
  antMatchers: /index,/login/**,/nonAuth/**,/favicon.ico,/common/**,/druid/**,/swagger**/**,/doc.html,/webjars/**,/v2/api-docs
#登录页验证码有效时间(单位分钟)/宽度/高度/位数
captcha:
  expiration: 2
  width: 120
  height: 50
  digit: 4
# 高德地图 IP定位
amap:
  ip-url: https://restapi.amap.com/v3/ip
  web-key: 051db8271016d725a284e90e9ad0da4e

# 代码生成
gen:
  # 作者
  author: zmzhou
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.github.zmzhou.easyboot.api.system
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
  # 自动去除表前缀，默认是true
  autoRemovePre: false

# Actuator Web 访问端口
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        # 暴漏的接口 - 所有接口
        include: "*"
# 日志配置
logging:
  config: classpath:log4j2.xml
  level:
    web: INFO
    com.github.zmzhou: INFO
    org.springframework: INFO
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health
#  client:
#    registryFetchIntervalSeconds: 5
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://192.168.137.67:8761}/eureka/
#info:
#  app:
#    name: @project.name@
#    version: @project.version@
#    description: @project.description@
#    spring-boot-version: @project.parent.version@
